# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            YJYGG's Site
tagline:          'Life builds us'
description:      'A collection of cherishable moments created and maintained by <a href="https://yueguoguo.github.io" target="_blank">@yueguoguo</a>.'
url:              https://yjygg.github.io
baseurl:          /

author:
  name:           'yueguoguo'
  url:            https://yueguoguo.github.io

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/yjygg/yjygg.github.io
