# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            YJYGG's Family Site
tagline:          'A collection of cherishable moments'
description:      'A brazen two-column <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that pairs a prominent sidebar with uncomplicated content. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:              https://yjygg.github.io
baseurl:          /

author:
  name:           'yueguoguo'
  url:            https://yueguoguo.github.io

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/yjygg/yjygg.github.io
